"""Graphical User Interface package for HR Toolkit."""

from __future__ import annotations

import sys
from tkinter import (
    BOTH,
    BOTTOM,
    Canvas,
    END,
    Frame,
    Label,
    LEFT,
    Menu,
    PhotoImage,
    RIGHT,
    StringVar,
    BooleanVar,
    Text,
    Tk,
    TkVersion,
    TOP,
    Toplevel,
    VERTICAL,
    Y,
    filedialog,
    messagebox,
    simpledialog,
    ttk,
)

from hr_toolkit import __version__, runlog

from .constants import *
from .scaling import *
from .widgets import *
from .helpers import *
from .task_runner import TaskRunner, TaskToken
from .app import HRToolkitApp, main

__all__ = [
    "HRToolkitApp",
    "main",
    "TaskRunner",
    "TaskToken",
    "CodexButton",
    "SidebarItem",
    "RoundedCard",
    "open_path",
    "desktop_dir",
    "make_result_output_dir",
    "default_output_parent_dir",
    "_scale_px",
    "_scale_float",
    "_fit_window_size",
    "_responsive_layout_mode",
    "_responsive_checkbox_columns",
    "_responsive_drawer_width",
    "_windows_work_area_for_root",
    "LAYOUT_MODE_WIDE",
    "LAYOUT_MODE_COMPACT",
    "LAYOUT_MODE_NARROW",
    "_clamp_ui_scale",
    "_indeterminate_progress_segment",
    "_forced_ui_scale",
    "_windows_dpi_for_root",
    "_detect_ui_scale",
    "_configure_tk_font_scaling",
    "_font_size",
    "_widget_ui_scale",
    "_paint_tool_icon",
    "_paint_codex_badge_icon",
    "_get_default_font_family",
    "_default_workspace_project_name",
    "_workspace_project_name_error",
    "_workspace_project_creation_target",
    "_workspace_project_create_error_message",
    "_workspace_trash_period_label",
    "_workspace_trash_title",
    "_workspace_trash_group_tool",
    "_workspace_trash_restore_location",
    "_workspace_trash_dialog_height",
    "_workspace_trash_ignore_enter",
    "_workspace_trash_matches",
    "_workspace_trash_deleted_text",
    "_default_result_dir_name",
    "_enable_high_dpi_rendering",
    "_set_windows_app_identity",
    "_install_crash_logging",
    "filedialog",
    "messagebox",
    "simpledialog",
    "Toplevel",
    "Frame",
    "Label",
    "Canvas",
    "PhotoImage",
    "Tk",
    "TkVersion",
    "runlog",
    "sys",
    "APP_DISPLAY_NAME",
    "APP_SUBTITLE",
    "COLOR_BG",
    "COLOR_SURFACE",
    "COLOR_PRIMARY",
    "TOOL_NAV_ITEMS",
    "TOOL_NAV_LABELS",
    "NAV_GROUPS",
    "TOOL_GROUP_LABELS",
    "MULTI_INPUT_TOOLS",
    "HISTORY_STATUS_LABELS",
    "HISTORY_DATE_FILTERS",
]
