from __future__ import annotations

import base64
import hashlib
import os
import tarfile
import tempfile
import unittest
import warnings as warnings_module
import zipfile
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

from openpyxl import Workbook
import py7zr

from hr_toolkit.common import inputs as inputs_module
from hr_toolkit.common.inputs import (
    SUPPORTED_ARCHIVE_SUFFIX_SET,
    archive_stem,
    archive_suffix,
    extract_archive_excel_files,
    extract_zip_excel_files,
    is_supported_archive_file,
    normalize_input_paths,
)


# Tiny RAR5 fixture from unrar2-cffi's Apache-2.0 test suite. Keeping a real
# compressed RAR in the regression test prevents a ZIP-only mock from passing.
_RAR_EQUIVALENCE_FIXTURE = base64.b64decode(
    "UmFyIRoHAM+QcwAADQAAAAAAAABP3noAgCMAQAAAAEIAAAAD5GYog3y5PE8dMwMAAQAAAENNVAlVAI/kz/dMKc1hCBJRIgrljlDW3tbWgi0NPUOG8d3f/nXg9hsDw9HjN7yro+0eWDk7l/Q0+U0/98ihUmRZwWQ4OHQgkC8AHQAAABEAAAADaH6JrXKYjkIdMw0AtIEAAHRlc3RfZmlsZS50eHQAwAkAy+0KK6BMaYKovpB2v4wNiHHVt6sj85oUFNyAJGt0IJAzABYAAAAWAAAAA5eDG2/xtTVPHTAOALSBAAB0ZXN0X2ZpbGUyLnR4dADwepl5VGhpcyBpcyBhbm90aGVyIHRlc3QhCntWdCCQNQAAAAAAAAAAAAMAAAAAAGkhUh0wEACkgQAAdGVzdGRpclx0ZXN0ZmlsZQDwHsYT+SN04JAsAAAAAAAAAAAAAwAAAAAAaSFSFDAHAO1BAAB0ZXN0ZGlyAPAexhPEPXsAQAcA"
)

# Generated by the RAR 7.23 CLI from a regular normal.xlsx and a relative
# link.xlsx symlink. It verifies that RAR redirections never become inputs.
_RAR_LINK_FIXTURE = base64.b64decode(
    "UmFyIRoHAQAzkrXlCgEFBgAFAQGAgACp5KyWKQIDC4YABIYApIMC5GiFIYAAAQtub3JtYWwueGxzeAoDE65biGqz83QYbm9ybWFsXXVXrjUCAxsABADtwwIAAAAAgAABCWxpbmsueGxzeAoDE65biGr6UJoYDwUBAAtub3JtYWwueGxzeB13VlEDBQQA"
)


def _make_xlsx_bytes() -> bytes:
    workbook = Workbook()
    workbook.active["A1"] = "测试"
    with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as handle:
        temp_path = Path(handle.name)
    try:
        workbook.save(temp_path)
        return temp_path.read_bytes()
    finally:
        temp_path.unlink(missing_ok=True)


class NormalizeInputPathsTest(unittest.TestCase):
    def test_single_path_is_wrapped(self) -> None:
        paths = normalize_input_paths("some.xlsx", "请选择文件。")
        self.assertEqual(len(paths), 1)
        self.assertTrue(paths[0].is_absolute())

    def test_empty_list_raises_with_message(self) -> None:
        with self.assertRaises(ValueError) as context:
            normalize_input_paths([], "请选择文件。")
        self.assertEqual(str(context.exception), "请选择文件。")


class ExtractZipExcelFilesTest(unittest.TestCase):
    def test_extracts_excel_files(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "input.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("目录/工资表.xlsx", _make_xlsx_bytes())
                archive.writestr("说明.txt", "忽略")
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual([path.name for path in files], ["工资表.xlsx"])
            self.assertEqual(warnings, [])

    def test_restores_gbk_encoded_filenames(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "gbk.zip"
            # Windows 资源管理器/WinRAR 用 GBK 存储文件名且不设置 UTF-8 标志。
            # zipfile 写入时无法直接生成这种 zip，因此先用等长 ASCII 名占位，
            # 再把归档里的文件名字节替换成 GBK 字节。
            gbk_name_bytes = "春苗5月考勤.xlsx".encode("gbk")
            placeholder = b"A" * (len(gbk_name_bytes) - 5) + b".xlsx"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr(placeholder.decode("ascii"), _make_xlsx_bytes())
            zip_path.write_bytes(zip_path.read_bytes().replace(placeholder, gbk_name_bytes))
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual([path.name for path in files], ["春苗5月考勤.xlsx"])
            self.assertEqual(warnings, [])

    def test_skips_path_traversal_members(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "evil.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("../escape.xlsx", _make_xlsx_bytes())
                archive.writestr("部门/../overwrite.xlsx", _make_xlsx_bytes())
                archive.writestr("正常.xlsx", _make_xlsx_bytes())
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual([path.name for path in files], ["正常.xlsx"])
            self.assertEqual(len(warnings), 2)
            self.assertTrue(all("不安全路径" in warning for warning in warnings))
            self.assertFalse((temp_dir / "escape.xlsx").exists())
            self.assertFalse(any(temp_dir.rglob("overwrite.xlsx")))

    def test_subdir_places_files_under_named_folder(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "social.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("明细.xlsx", _make_xlsx_bytes())
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings, subdir="social")
            self.assertEqual(len(files), 1)
            self.assertEqual(files[0].parent.name, "social")

    def test_bad_zip_returns_empty_with_warning(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "broken.zip"
            zip_path.write_bytes(b"not a zip")
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertEqual(len(warnings), 1)
            self.assertIn("解压失败", warnings[0])

    def test_preserves_self_extracting_zip_compatibility(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "self-extracting.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("工资表.xlsx", _make_xlsx_bytes())
            zip_path.write_bytes(b"MZ\x90\x00synthetic-stub" + zip_path.read_bytes())
            warnings: list[str] = []
            files = extract_archive_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual([path.name for path in files], ["工资表.xlsx"])
            self.assertEqual(warnings, [])

    def test_rejects_zip_with_too_many_members_before_extracting(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "many.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("1.xlsx", b"one")
                archive.writestr("2.xlsx", b"two")
            warnings: list[str] = []
            with patch("hr_toolkit.common.inputs.ARCHIVE_MAX_MEMBERS", 1):
                files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertIn("文件数量超过", warnings[0])
            self.assertFalse(any(temp_dir.glob("archive_*")))

    def test_rejects_zip_whose_expanded_size_exceeds_limit(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "large.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("large.xlsx", b"x" * 128)
            warnings: list[str] = []
            with patch("hr_toolkit.common.inputs.ARCHIVE_MAX_TOTAL_BYTES", 64):
                files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertIn("总大小超过", warnings[0])

    def test_rejects_zip_when_temporary_disk_space_is_insufficient(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "space.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("data.xlsx", b"data")
            disk_usage = type("DiskUsage", (), {"total": 1, "used": 1, "free": 0})()
            warnings: list[str] = []
            with patch("hr_toolkit.common.inputs.shutil.disk_usage", return_value=disk_usage):
                files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertIn("临时磁盘空间不足", warnings[0])

    def test_rejects_abnormal_compression_ratio(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "ratio.zip"
            with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr("compressed.xlsx", b"x" * 4096)
            warnings: list[str] = []
            with (
                patch("hr_toolkit.common.inputs.ARCHIVE_RATIO_CHECK_MIN_BYTES", 1),
                patch("hr_toolkit.common.inputs.ARCHIVE_MAX_COMPRESSION_RATIO", 2),
            ):
                files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertIn("压缩比例异常", warnings[0])

    def test_skips_symbolic_link_members(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "link.zip"
            link = zipfile.ZipInfo("outside.xlsx")
            link.create_system = 3
            link.external_attr = 0o120777 << 16
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr(link, "../outside.xlsx")
                archive.writestr("normal.xlsx", _make_xlsx_bytes())
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual([path.name for path in files], ["normal.xlsx"])
            self.assertTrue(any("链接文件" in warning for warning in warnings))

    def test_rejects_duplicate_member_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "duplicate.zip"
            with warnings_module.catch_warnings():
                warnings_module.simplefilter("ignore", UserWarning)
                with zipfile.ZipFile(zip_path, "w") as archive:
                    archive.writestr("工资表.xlsx", b"first")
                    archive.writestr("工资表.xlsx", b"second")
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertIn("重复路径", warnings[0])
            self.assertFalse(any(temp_dir.glob("archive_*")))

    def test_rejects_duplicate_paths_with_dot_alias(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "duplicate-alias.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("部门/工资表.xlsx", b"first")
                archive.writestr("部门/./工资表.xlsx", b"second")
            warnings: list[str] = []
            files = extract_zip_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertIn("重复路径", warnings[0])

    def test_rejects_file_directory_prefix_conflict_before_extracting(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            temp_dir = Path(temp_root)
            zip_path = temp_dir / "prefix-conflict.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("部门", b"not a directory")
                archive.writestr("部门/工资表.xlsx", _make_xlsx_bytes())
            warnings: list[str] = []
            files = extract_archive_excel_files(zip_path, temp_dir, warnings)
            self.assertEqual(files, [])
            self.assertIn("文件与目录路径冲突", warnings[0])
            self.assertFalse(any(temp_dir.glob("archive_*")))


class ArchiveFormatCompatibilityTest(unittest.TestCase):
    def test_python38_py7zr_uses_bundled_7zip_compatibility_path(self) -> None:
        legacy_py7zr = SimpleNamespace(SevenZipFile=object)
        with tempfile.TemporaryDirectory() as temp_root:
            root = Path(temp_root)
            executable = root / "7z.exe"
            executable.write_bytes(b"runtime")
            with (
                patch.dict("sys.modules", {"py7zr": legacy_py7zr}),
                patch.object(
                    inputs_module,
                    "_bundled_7zip_executable",
                    return_value=executable,
                ),
                patch.object(inputs_module, "_extract_with_7zip_cli") as extractor,
            ):
                inputs_module._extract_7z(
                    root / "input.7z",
                    root / "extract",
                    root,
                    [],
                )

        extractor.assert_called_once()
        self.assertEqual(extractor.call_args.args[0], executable)

    def test_7zip_listing_parser_marks_links_and_preserves_sizes(self) -> None:
        listing = """7-Zip 26.02

----------
Path = normal.xlsx
Size = 12
Packed Size = 8
Folder = -
Attributes = A
Encrypted = -

Path = link.xlsx
Size = 11
Packed Size = 7
Folder = -
Attributes = lrwxrwxrwx
Symbolic Link = normal.xlsx
Encrypted = -
"""
        members = inputs_module._parse_7zip_slt(listing)

        self.assertEqual([member.name for member in members], ["normal.xlsx", "link.xlsx"])
        self.assertEqual(members[0].file_size, 12)
        self.assertEqual(members[0].compress_size, 8)
        self.assertFalse(members[0].is_link)
        self.assertTrue(members[1].is_link)

    def test_supported_suffixes_and_multisuffix_stems_are_explicit(self) -> None:
        self.assertEqual(
            SUPPORTED_ARCHIVE_SUFFIX_SET,
            {
                ".zip",
                ".rar",
                ".7z",
                ".tar",
                ".tar.gz",
                ".tgz",
                ".tar.bz2",
                ".tbz2",
                ".tar.xz",
                ".txz",
            },
        )
        self.assertEqual(archive_suffix("人事资料.TAR.GZ"), ".tar.gz")
        self.assertEqual(archive_stem("人事资料.tar.gz"), "人事资料")
        self.assertTrue(is_supported_archive_file("人事资料.rar"))
        self.assertFalse(is_supported_archive_file("人事资料.gz"))

    def test_same_content_has_identical_manifest_in_every_supported_format(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            root = Path(temp_root)
            rar_path = root / "same-content.rar"
            rar_path.write_bytes(_RAR_EQUIVALENCE_FIXTURE)

            with patch("hr_toolkit.common.inputs.is_supported_excel_file", return_value=True):
                reference_files = extract_archive_excel_files(rar_path, root / "rar-reference", [])
            reference_payloads = {
                path.relative_to(root / "rar-reference" / "archive_1").as_posix(): path.read_bytes()
                for path in reference_files
            }
            self.assertEqual(
                reference_payloads,
                {
                    "test_file.txt": b"This is for test.",
                    "test_file2.txt": b"This is another test!\n",
                    "testdir/testfile": b"",
                },
            )

            source_root = root / "source"
            for relative, payload in reference_payloads.items():
                source = source_root / relative
                source.parent.mkdir(parents=True, exist_ok=True)
                source.write_bytes(payload)

            archives = [rar_path]
            zip_path = root / "same-content.zip"
            with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
                for relative in reversed(sorted(reference_payloads)):
                    archive.write(source_root / relative, relative)
            archives.append(zip_path)

            seven_zip_path = root / "same-content.7z"
            with py7zr.SevenZipFile(seven_zip_path, "w") as archive:
                for relative in reversed(sorted(reference_payloads)):
                    archive.write(source_root / relative, relative)
            archives.append(seven_zip_path)

            tar_modes = {
                ".tar": "w",
                ".tar.gz": "w:gz",
                ".tgz": "w:gz",
                ".tar.bz2": "w:bz2",
                ".tbz2": "w:bz2",
                ".tar.xz": "w:xz",
                ".txz": "w:xz",
            }
            for suffix, mode in tar_modes.items():
                tar_path = root / f"same-content{suffix}"
                with tarfile.open(tar_path, mode) as archive:
                    for relative in reversed(sorted(reference_payloads)):
                        archive.add(source_root / relative, relative)
                archives.append(tar_path)

            # 后缀和真实内容不一致时仍按文件签名识别，避免不同压缩工具改名后解析分叉。
            mislabeled_path = root / "rar-content.zip"
            mislabeled_path.write_bytes(_RAR_EQUIVALENCE_FIXTURE)
            archives.append(mislabeled_path)

            expected_manifest = [
                (relative, hashlib.sha256(payload).hexdigest())
                for relative, payload in sorted(reference_payloads.items())
            ]
            for index, archive_path in enumerate(archives):
                extract_dir = root / f"extract-{index}"
                warnings: list[str] = []
                with patch("hr_toolkit.common.inputs.is_supported_excel_file", return_value=True):
                    files = extract_archive_excel_files(archive_path, extract_dir, warnings)
                manifest = [
                    (
                        path.relative_to(extract_dir / "archive_1").as_posix(),
                        hashlib.sha256(path.read_bytes()).hexdigest(),
                    )
                    for path in files
                ]
                with self.subTest(archive=archive_path.name):
                    self.assertEqual(warnings, [])
                    self.assertEqual(manifest, expected_manifest)

    @unittest.skipIf(os.name == "nt", "creating symlinks may require Windows developer mode")
    def test_7z_link_is_skipped_instead_of_becoming_an_input_file(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            root = Path(temp_root)
            source = root / "normal.xlsx"
            source.write_bytes(_make_xlsx_bytes())
            link = root / "link.xlsx"
            link.symlink_to(source)
            archive_path = root / "links.7z"
            with py7zr.SevenZipFile(archive_path, "w", dereference=False) as archive:
                archive.write(source, arcname=source.name)
                archive.write(link, arcname=link.name)

            warnings: list[str] = []
            files = extract_archive_excel_files(archive_path, root / "extract", warnings)
            self.assertEqual([path.name for path in files], ["normal.xlsx"])
            self.assertTrue(any("链接文件" in warning for warning in warnings))

    def test_rar_link_is_skipped_instead_of_becoming_an_input_file(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            root = Path(temp_root)
            archive_path = root / "links.rar"
            archive_path.write_bytes(_RAR_LINK_FIXTURE)
            warnings: list[str] = []
            files = extract_archive_excel_files(archive_path, root / "extract", warnings)
            self.assertEqual([path.name for path in files], ["normal.xlsx"])
            self.assertEqual(files[0].read_bytes(), b"normal")
            self.assertTrue(any("链接文件" in warning for warning in warnings))

    def test_corrupt_non_zip_archives_never_leave_partial_results(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            root = Path(temp_root)
            source = root / "normal.xlsx"
            source.write_bytes(_make_xlsx_bytes())

            valid_7z = root / "valid.7z"
            with py7zr.SevenZipFile(valid_7z, "w") as archive:
                archive.write(source, arcname=source.name)
            valid_tar_gz = root / "valid.tar.gz"
            with tarfile.open(valid_tar_gz, "w:gz") as archive:
                archive.add(source, arcname=source.name)

            corrupt_payloads = {
                "corrupt.rar": _RAR_EQUIVALENCE_FIXTURE[: len(_RAR_EQUIVALENCE_FIXTURE) // 2],
                "corrupt.7z": valid_7z.read_bytes()[: valid_7z.stat().st_size // 2],
                "corrupt.tar.gz": valid_tar_gz.read_bytes()[: valid_tar_gz.stat().st_size // 2],
            }
            for index, (name, payload) in enumerate(corrupt_payloads.items()):
                archive_path = root / name
                archive_path.write_bytes(payload)
                extract_root = root / f"corrupt-extract-{index}"
                warnings: list[str] = []
                files = extract_archive_excel_files(archive_path, extract_root, warnings)
                with self.subTest(archive=name):
                    self.assertEqual(files, [])
                    self.assertEqual(len(warnings), 1)
                    self.assertIn("解压失败", warnings[0])
                    self.assertFalse(any(extract_root.glob("archive_*")))

    def test_encrypted_7z_is_rejected_without_partial_results(self) -> None:
        with tempfile.TemporaryDirectory() as temp_root:
            root = Path(temp_root)
            source = root / "normal.xlsx"
            source.write_bytes(_make_xlsx_bytes())
            archive_path = root / "encrypted.7z"
            with py7zr.SevenZipFile(
                archive_path,
                "w",
                password="secret",
                header_encryption=True,
            ) as archive:
                archive.write(source, arcname=source.name)

            warnings: list[str] = []
            files = extract_archive_excel_files(archive_path, root / "extract", warnings)
            self.assertEqual(files, [])
            self.assertEqual(len(warnings), 1)
            self.assertIn("压缩包带密码", warnings[0])
            self.assertFalse(any((root / "extract").glob("archive_*")))


if __name__ == "__main__":
    unittest.main()
